[package]
name = "isotope"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
seahorse = "2.1"
simple-home-dir = "0.2.0"
serde_json = "1.0.107"
serde = {version= "1.0.188", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
aws-config = "0.56.1"
colored = "2.0.4"
futures = "0.3.28"
async-trait = "0.1.73"
aws-sdk-s3 = "0.33.0"
aws-sdk-macie = "0.33.0"
v = "0.1.0"
aws-sdk-config = "0.33.0"
clap = { version = "4.4.6", features = ["derive"] }
